name: online_shopping
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get:
  iconsax:
  carousel_slider: ^4.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.6
  provider: ^6.0.3 
  path: any
  sqflite_common_ffi: any
  image_picker: ^0.8.4+4
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  fan_carousel_image_slider: ^1.0.1
  flutter_pannable_rating_bar: ^2.7.2+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/login.jpg
    - image/logo_soisu.png
    - image/welcome.jpg
    - image/soiclothing.png
    - image/jasbrand.png
    - image/soibrand.png
    - image/1.jpg
    - image/2.jpg
    - image/3.jpg
    - image/4.jpg
    - image/5.jpg
    - image/kbzpay.jpg
    - image/ayapay.jpg
    - image/wavepay.jpg
    - image/orderconfirm.png
    - image/ninjavan.jpg
    - image/btbestie1.jpg
    - image/btbestie2.jpg
    - image/btbestie3.jpg
    - image/btbestie4.jpg
    - image/btbestie5.jpg
    - image/btmocha1.jpg
    - image/btmocha2.jpg
    - image/btmocha3.jpg
    - image/btmocha4.jpg
    - image/btshort1.jpg
    - image/btshort2.jpg
    - image/btshort3.jpg
    - image/btshort4.jpg
    - image/btshort5.jpg
    - image/btsummer1.jpg
    - image/btsummer2.jpg
    - image/btsummer3.jpg
    - image/btsummer4.jpg
    - image/btsummer5.jpg
    - image/btsummer6.jpg
    - image/btsummer7.jpg
    - image/cashpay.jpg
    - image/hazelarm1.jpg
    - image/hazelarm2.jpg
    - image/hazelarm3.jpg
    - image/hazelarm4.jpg
    - image/hazelarm5.jpg
    - image/hazelcoral1.jpg
    - image/hazelcoral2.jpg
    - image/hazelcoral3.jpg
    - image/hazelcoral4.jpg
    - image/hazelcoral5.jpg
    - image/hazelcoral6.jpg
    - image/hazeldress1.jpg
    - image/hazeldress2.jpg
    - image/hazeldress3.jpg
    - image/hazeldress4.jpg
    - image/hazeldress5.jpg
    - image/hazelella1.jpg
    - image/hazelella2.jpg
    - image/hazelella3.jpg
    - image/hazelella4.jpg
    - image/hazelella5.jpg
    - image/hazelella6.jpg
    - image/hazelflory1.jpg
    - image/hazelflory2.jpg
    - image/hazelflory3.jpg
    - image/hazelflory4.jpg
    - image/hazelflory5.jpg
    - image/hazelhana1.jpg
    - image/hazelhana2.jpg
    - image/hazelhana3.jpg
    - image/hazelhana4.jpg
    - image/hazelhana5.jpg
    - image/hazelintern1.jpg
    - image/hazelintern2.jpg
    - image/hazelintern3.jpg
    - image/hazelintern4.jpg
    - image/hazelintern5.jpg
    - image/hazelirene1.jpg
    - image/hazelirene2.jpg
    - image/hazelirene3.jpg
    - image/hazelirene4.jpg
    - image/hazelirene5.jpg
    - image/hazelpant1.jpg
    - image/hazelpant2.jpg
    - image/hazelpant3.jpg
    - image/hazelpant4.jpg
    - image/hazelpant5.jpg
    - image/hazelrain1.jpg
    - image/hazelrain2.jpg
    - image/hazelrain3.jpg
    - image/hazelrain4.jpg
    - image/hazelrain5.jpg
    - image/hazelskirt1.jpg
    - image/hazelskirt2.jpg
    - image/hazelskirt3.jpg
    - image/hazelskirt4.jpg
    - image/hazeltop1.jpg
    - image/hazeltop2.jpg
    - image/hazeltop3.jpg
    - image/hazeltop4.jpg
    - image/hazeltop5.jpg
    - image/hazeltube1.jpg
    - image/hazeltube2.jpg
    - image/hazeltube3.jpg
    - image/hazeltube4.jpg
    - image/hazeltube5.jpg
    - image/hazeltube6.jpg
    - image/mozedream1.jpg
    - image/mozedream2.jpg
    - image/mozedream3.jpg
    - image/mozedream4.jpg
    - image/mozedream5.jpg
    - image/mozekiz1.jpg
    - image/mozekiz2.jpg
    - image/mozekiz3.jpg
    - image/mozekiz4.jpg
    - image/mozekiz5.jpg
    - image/mozelongsk1.jpg
    - image/mozelongsk2.jpg
    - image/mozelongsk3.jpg
    - image/mozelongsk4.jpg
    - image/mozelongsk5.jpg
    - image/mozelove1.jpg
    - image/mozelove2.jpg
    - image/mozelove3.jpg
    - image/mozelove4.jpg
    - image/mozelove5.jpg
    - image/mozemesh1.jpg
    - image/mozemesh2.jpg
    - image/mozemesh3.jpg
    - image/mozemesh4.jpg
    - image/mozemesh5.jpg  
    - image/mozepuzzle1.jpg
    - image/mozepuzzle2.jpg
    - image/mozepuzzle3.jpg
    - image/mozepuzzle4.jpg
    - image/mozepuzzle5.jpg
    - image/mozeswirl1.jpg
    - image/mozeswirl2.jpg
    - image/mozeswirl3.jpg
    - image/mozeswirl4.jpg
    - image/mozeswirl5.jpg
    - image/placherry1.jpg
    - image/placherry2.jpg
    - image/placherry3.jpg
    - image/placherry4.jpg
    - image/placherry5.jpg
    - image/plalinen1.jpg
    - image/plalinen2.jpg
    - image/plalinen3.jpg
    - image/plalinen4.jpg
    - image/plalinen5.jpg
    - image/plaribbon1.jpg
    - image/plaribbon2.jpg
    - image/plaribbon3.jpg
    - image/plaribbon4.jpg
    - image/plaribbon5.jpg
    - image/profile.jpg
    - image/rmcorset1.jpg
    - image/rmcorset2.jpg
    - image/rmcorset3.jpg
    - image/rmcorset4.jpg
    - image/rmcorset5.jpg
    - image/rmcorset6.jpg
    - image/rmultrapant1.jpg
    - image/rmultrapant2.jpg
    - image/rmultrapant3.jpg
    - image/rmultrapant4.jpg
    - image/trinbasic1.jpg
    - image/trinbasic2.jpg
    - image/trinbasic3.jpg
    - image/trinbasic4.jpg
    - image/trincar1.jpg
    - image/trincar2.jpg
    - image/trincar3.jpg
    - image/trincar4.jpg
    - image/trindress1.jpg
    - image/trindress2.jpg
    - image/trindress3.jpg
    - image/trindress4.jpg
    - image/trindress5.jpg
    - image/trinmini1.jpg
    - image/trinmini2.jpg
    - image/trinmini3.jpg
    - image/trinplain1.jpg
    - image/trinplain2.jpg
    - image/trinplain3.jpg
    - image/trinplain4.jpg
    - image/trinribbon1.jpg
    - image/trinribbon2.jpg
    - image/trinribbon3.jpg
    - image/trinribbon4.jpg
    - image/trinset1.jpg
    - image/trinset2.jpg
    - image/trinset3.jpg
    - image/trinset4.jpg
    - image/yourbutton1.jpg
    - image/yourbutton2.jpg
    - image/yourbutton3.jpg
    - image/yourbutton4.jpg
    - image/yourbutton5.jpg
    - image/yourcamiso1.jpg
    - image/yourcamiso2.jpg
    - image/yourcamiso3.jpg
    - image/yourcamiso4.jpg
    - image/yourcamiso5.jpg
    - image/yourmabel1.jpg
    - image/yourmabel2.jpg
    - image/yourmabel3.jpg
    - image/yourmabel4.jpg
    - image/yourmabel5.jpg
    - image/soisu.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
